feat: add CHANGELOG entry for container version bump to Python 3.8 / …
StackStorm/stackstorm-k8s pull request #282
Opened 2022-02-13 02:32 UTC by jstaph

Adds CHANGELOG line to note future bump to Python 3.8 / Ubuntu 20

2022-02-13 12:13 UTC, armab requested changes
Thanks!

Found a minor thing.
Could you please also update the tests here for the new py version?
https://github.com/StackStorm/stackstorm-ha/blob/62b33259bb72c60801ba8326c435276289b6b51c/tests/st2tests.sh#L7-L13

2022-02-13 17:28 UTC, armab approved these changes
The tests should pass once we release the `v3.7.0` + updated Docker images.

Thanks for the help preparing it! :+1:

2022-02-13 17:56 UTC, jstaph commented
You bet, and nice catch on the tests!  Much appreciated!

2022-05-06 22:34 UTC, cognifloyd approved these changes

2022-05-06 23:00 UTC, merged