Add Ability to Write/Use st2.secrets.conf from K8s Secret
StackStorm/stackstorm-k8s pull request #289
Opened 2022-02-25 21:05 UTC by eric-al

This PR adds the capability to define '/etc/st2/st2.secret.conf' in a Kubernetes secret.  No longer will users need things like helm-secrets to safely store secret values that ultimately wind up in /etc/st2/*.conf.

If this is defined, the contents of key 'st2.secret.conf' within the defined secret name will be written to '/etc/st2/st2.secret.conf' on all pods.  In addition, '--config-file=/etc/st2/st2.secrets.conf' will be added to the end of the command line arguments for all pods, superseding all other configuration values.

This addresses the Comment-Based-TODO here:  https://github.com/alertlogic/stackstorm-ha/blob/master/templates/configmaps_st2-conf.yaml#L16

2022-02-25 21:24 UTC, sanketgawade approved these changes
+1

2022-03-03 18:32 UTC, cognifloyd commented
Could you add a unit test that inspects the command? You can see other unit tests in `tests/unit/`.
The test should probably ensure that `command` is defined on all deployments and jobs and that it includes the expected args.

2022-03-24 22:35 UTC, cognifloyd requested changes
As this PR is made from an organization repo, github doesn't allow you to give us permission to update the branch. So, I can't merge in master or do any cleanups.

Would you please:
- merge in master
- minor cleanup in comments

For the unit tests, I believe something like this should work: https://gist.github.com/cognifloyd/362a3637e43e199a013897f74454c14e

I haven't tested it, but I think that'll cover all of the testing boilerplate around these conf files.

2022-05-11 11:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/StackStorm/stackstorm-k8s?pullRequest=289) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/StackStorm/stackstorm-k8s?pullRequest=289) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/StackStorm/stackstorm-k8s?pullRequest=289) it.</sub>

2022-07-09 20:12 UTC, cognifloyd commented
Closing in favor of #319 since Eric no longer has access to the @eric-al account and we as maintainers cannot edit this PR to help him with it.

2022-07-09 20:12 UTC, closed without merging