wip datastore secret name
StackStorm/stackstorm-k8s pull request #363
Opened 2023-03-08 15:38 UTC by guzzijones

2023-03-08 15:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/StackStorm/stackstorm-k8s?pullRequest=363) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/StackStorm/stackstorm-k8s?pullRequest=363) before we can accept your contribution.<br/><hr/>**aj** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/StackStorm/stackstorm-k8s?pullRequest=363) it.</sub>

2023-03-10 19:43 UTC, guzzijones commented
Any thoughts on this?

2023-03-12 06:27 UTC, cognifloyd requested changes
I think we're going to need to do something like this for many of our secrets.

What about adding a helper that returns the name of the secret to use? That can handle returning the custom secret name if provided, or else the default name. Use that helper in the be deployments and jobs.

Then, in the secret file, wrap the whole resource in an if block. If there is a custom resource name, do not create the chart-managed secret.

2023-03-20 20:46 UTC, cognifloyd commented
Something like #359 would be great for the datastore secret.

2023-05-12 18:33 UTC, guzzijones commented
I am going to start on this with the changes you requested.

2023-05-15 19:08 UTC, closed without merging