Remove redundant [credentials] header
StackStorm/stackstorm-k8s pull request #371
Opened 2023-08-21 22:02 UTC by cars

Remove redundant [credentials] header for client config that causes st2 commands to fail.
see issue: #370

2023-08-21 22:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/StackStorm/stackstorm-k8s?pullRequest=371) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/StackStorm/stackstorm-k8s?pullRequest=371) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/StackStorm/stackstorm-k8s?pullRequest=371) it.</sub>

2023-08-23 11:57 UTC, armab requested changes
Thanks for the contribution!

Could you please update the https://github.com/StackStorm/stackstorm-k8s/blob/master/CHANGELOG.md as well?

Otherwise looks good 👍

2023-08-23 16:34 UTC, cars commented
Changelog updated

2023-08-25 11:10 UTC, armab approved these changes

2023-08-25 11:10 UTC, merged

2023-08-25 11:10 UTC, armab commented
Thanks!